name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --requirement requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --requirement requirements.txt
        pip install --requirement requirements-test.txt

    - name: Run black
      run: |
        black --config pyproject.toml .

    - name: Run flake8
      run: |
        flake8 --config setup.cfg .

    - name: Run flake8
      run: |
        black --config pyproject.toml .

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
